name: Angular Calculator Actions
uses: amondnet/vercel-action@v25

on:
  push:
    branches:
    - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Branch Checkout
        uses: actions/checkout@v2

      - name: Node install
        uses: actions/setup-node@v2
        with:
          node-version: '16.14.0'

      - name: Install dependencies
        run: npm install

      - name: Test Application
        run: npm run test:headless

      - name: Build App
        run: npm run build
