name: Angular Calculator Actions
uses: amondnet/vercel-action@v25
on:
  push:
    branches:
    - main

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16.14.0'

      - run: npm install
      - run: npm run build

  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Run tests
        run: npm run test:headless

  deploy:
    needs: [build, test]
    runs-on: ubuntu-latest
    steps:
      - name: Start deploy
        uses: bobheadxi/deployments@v0.4.3
        id: deployment
        with:
          step: start
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Checkout branch
        uses: actions/checkout@v2

      - name: Unit tests
        run: npm run test:headless

      - name: Deploy vercel
        if: success()
        uses: amondnet/vercel/action@v20
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }} # Required
          github-token: ${{ secrets.GITHUB_TOKEN }} #Optional
          vercel-args: '--prod' #Optional
          working-directory: ./dist/angular-calculator
